# Generated by Django 4.1.13 on 2024-01-07 23:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='component_type',
            fields=[
                ('component_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='components',
            fields=[
                ('component_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('purchase_date', models.DateField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('image', models.URLField(blank=True, null=True)),
                ('component_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.component_type')),
            ],
        ),
        migrations.CreateModel(
            name='equipment_type',
            fields=[
                ('equipment_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='equipments',
            fields=[
                ('equipment_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('components', models.ManyToManyField(to='app.components')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.equipment_type')),
            ],
        ),
        migrations.CreateModel(
            name='labor_type',
            fields=[
                ('labor_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('labor_name', models.CharField(max_length=30, unique=True)),
                ('value', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='shipping_guide',
            fields=[
                ('guide_id', models.AutoField(primary_key=True, serialize=False)),
                ('shipping_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('delivery_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='warehouse',
            fields=[
                ('warehouse_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('postal_code', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='supplier',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('warehouse', models.ManyToManyField(to='app.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='production',
            fields=[
                ('production_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('production_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('production_end', models.DateTimeField(null=True)),
                ('status', models.BooleanField(null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.equipments')),
                ('labor_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.labor_type')),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(max_length=20)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.equipments')),
                ('shipping_guide', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.shipping_guide')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='components',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.supplier'),
        ),
    ]
