# Generated by Django 4.1.13 on 2024-01-08 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipments',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
