# Generated by Django 4.1.13 on 2024-01-08 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_equipments_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping_guide',
            name='shipping_date',
            field=models.DateTimeField(null=True),
        ),
    ]
